### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by jaredpetersen** [aaroncarsonart/TentsNTrailsTesting#1]
A README would be very helpful

**Comment by jaredpetersen** [comment]
There's a minor README now, but do you think we need to add a more thorough one. @aaroncarsonart I know that you were planning on writing one up.

**Comment by aaroncarsonart** [comment]
What you wrote up definitely gives important info for setting everything up.  I was thinking of doing a quick tutorial with screenshots showing how to run the tests in eclipse as JUnit tests.  I was looking into it, and I guess I can host images on Github in this repository's wiki, so maybe I'll do the tutorial on there.
