### ISSUE TITLE
Give it a License

### ISSUE THREAD

**Issue by jaredpetersen** [aaroncarsonart/TentsNTrailsTesting#2]
This repository doesn't have a license. I would recommend licensing it under the MIT license.

**Comment by aaroncarsonart** [comment]
Need to look into this.  I have never put a license on code before, although I have read about it.  Since I added you, why don't you update it, and I will take note?  Thanks

**Comment by jaredpetersen** [comment]
Well, it depends on what kind of license we all want. If we want it to just be totally free and open source, I would recommend the MIT License (http://opensource.org/licenses/MIT). I've used it in the past. This is just a testing suite and it's all based off of a tutorial so I'm not sure that we can really justify  "owning" it. Here's more info: http://choosealicense.com/

**Comment by jaredpetersen** [comment]
Gave it the MIT License.
